name: Build and deploy Jekyll site

on:
  push:
    branches: [ main ]  # or master, depending on your default branch

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/configure-pages@v2
      - name: Deploy
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-path: ./_site  # Tell GitHub to use _site