name: Build and deploy Jekyll site

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Debug - Check Ruby version
        run: ruby --version
      
      - name: Build and Deploy Jekyll Site
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages

      - name: Debug - List files
        run: |
          echo "Repository contents after action:"
          ls -la