name: Build and deploy Jekyll site

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Specify a Ruby version that supports bundler 2.5.7
          bundler-cache: true

      - name: Debug - Check Ruby version
        run: ruby --version
      
      - name: Build and Deploy Jekyll Site
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
          jekyll_src: '.'
          pre_build_commands: 'gem install bundler:2.5.7'  # Ensure correct bundler version

      - name: Debug - List files
        run: |
          echo "Repository contents after action:"
          ls -la